version: '3.8'

services:
  ml-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml-api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ../data/models:/app/data/models
      - ../data/datasets:/app/data/datasets
    depends_on:
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  n8n:
    image: n8nio/n8n
    env_file: .env
    ports:
      - "5678:5678"
    volumes:
      - ../orchestration/n8n_workflows:/home/node/.n8n/workflows
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ../monitoring/dashboards/grafana:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus:/etc/prometheus

volumes:
  postgres_data: