affinity:
  device: cpu
  model_path: C:\Users\ADM\Documents\GitHub\master\data\models\production\account_affinity.onnx
anomaly:
  device: cpu
  model_path: C:\Users\ADM\Documents\GitHub\master\data\models\production\anomaly_detector.pt
yolo_screenshot:
  conf_threshold: 0.25
  device: cpu
  iou_threshold: 0.45
  model_path: C:\Users\ADM\Documents\GitHub\master\data\models\production\tiktok_ui_detector.pt
  training:
    batch: 16
    data_yaml: C:\Users\ADM\Documents\GitHub\master\data\datasets\tiktok_ui\data.yaml
    epochs: 100
    imgsz: 640
yolo_video:
  device: cpu
  model_path: C:\Users\ADM\Documents\GitHub\master\data\models\production\tiktok_video_analyzer.pt
