name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Docker Hub credentials from secrets
        run: |
          echo "DOCKER_USER=${{ secrets.DOCKER_USER }}" >> $GITHUB_ENV
          echo "DOCKER_PAT=${{ secrets.DOCKER_PAT }}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.unified-railway
          push: true
          tags: agora90/stakas-mvp:latest
          platforms: linux/amd64,linux/arm64
